version: "3.6"

x-omnia: &default
  build:
    context: ../
    dockerfile: Dockerfile.omnia-dev
  environment: &env
    ETH_GAS: 7000000

services:
  feed:
    <<: *default
    network_mode: host
    volumes:
      - nix:/nix
      - ../:/src 
      - /home/admin/keystore:/etc/omnia/keystore
      - /home/admin/.ethereum/keystore:/home/admin/.ethereum/keystore
      - /home/admin/.ethereum/keystore/.pass:/home/admin/.ethereum/keystore/.pass
      - /home/admin/keystore/.pass:/etc/omnia/password
      - ./ssb/feed:/root/.ssb/secret
      - ../omnia/config/feed.conf:/src/omnia/config/feed.conf
    environment:
      <<: *env
      OMNIA_FILE_SET: /src/omnia/config/feed.conf
      OMNIA_CONFIG: /src/omnia/config/feed.conf

  relay:
    <<: *default
    volumes:
      - nix:/nix
      - ../:/src
      - ../testchain/keystore:/etc/omnia/keystore
      - ../testchain/keystore/password:/etc/omnia/password
      - ./ssb/relay:/root/.ssb/secret
    environment:
      <<: *env
      OMNIA_FILE_SET: /src/omnia/config/relay-testchain.conf
      OMNIA_STR_ethereum_from: "0x436177e390e835959c82afc56e063bd032ad57fb"
      SSB_STR_connections_incoming_net__external: relay
      SSB_STR_connections_incoming_ws__external: relay

volumes:
  nix:
